name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [closed]
    branches:
      - main
      - staging
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            curl -X GET "https://api.vercel.com/v1/integrations/deploy/prj_7x09eDIg4m690jtJ3kMHQviwRnxk/z61OeZa3ik"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            curl -X GET "https://api.vercel.com/v1/integrations/deploy/prj_7x09eDIg4m690jtJ3kMHQviwRnxk/yDwsWYVDS1"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            curl -X GET "https://api.vercel.com/v1/integrations/deploy/prj_7x09eDIg4m690jtJ3kMHQviwRnxk/lGNF3CXN45"
          fi
